### ISSUE TITLE
Ebay 0720

### ISSUE THREAD

**Issue by CICICheung** [JMLUSA/ads13afs13fsa#7]
1. 检查Ebay 邮箱查看投诉回复，没有收到Ebay 回复信息。
2.Ebay 平台JMLtextile 成人泳镜产品链接：http://www.ebay.com/itm/JML-Swim-Goggles-Waterproof-UV-Protection-Anti-Fog-Adult-Swimming-Goggles-Black-/263084916476?var=&hash=item3d41153efc:m:mgfusmGQELK4FBL8aQZyJaw

Note: 昨天发到新Ebay 平台的产品，今天都看不到，重新上传了再发产品链接过来

3.Note: 
（1）Ebay 注册用商业账户
（2）Listing 发布产品中选择“immediate payment”

4. Ebay 平台JMLtextile 账号：jmlpollytex@hotmail.com ; 密码：Chen!0124 
User ID: jmltextile 
Business Name: JML Trading
Address: 10020 Pioneer Blvd. Ste 108, City:Santa Fe Springs, State: California
Zip:90670; Country:United States
Primary Telephone: +1323xxxxx08 

Paypal Account: jmlpollytex@hotmail.com

5.Ebay 新平台信息：
公司名称 JIN MEI LUN TRADING LLC
邮箱 merryhome2017@hotmail.com
手机号18932679008
地址：1075 S. Vail Ave. MONTEBELLO，CA 90640
Paypal账号:jianliyan_107728@126.com （临时）
@furspotusa @Lisa-JML

**Comment by furspotusa** [comment]
新平台的密碼能傳上來嗎？

**Comment by CICICheung** [comment]
新平台账号：merryhome2017@hotmail.com 密码：lisaabc123
